ExtraPortal/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExtraPortal.Models;
using ExtraPortal.Services;

namespace ExtraPortal.Controllers
{
    public class SystemController : Controller
    {
        SystemService _SystemService = new SystemService();
        // GET: System
          
        [ChildActionOnly]
        public ActionResult ModuleAccess()
        {

            UserAccessRightsModel _AccessModel = new UserAccessRightsModel();
            _AccessModel.mainmodule = _SystemService.MainModules();
            _AccessModel.modules = _SystemService.Modules();

            //AccessModel.OperatorID = Session["KE_UserName"].ToString();
            //AccessModel.RoleID = Session["KE_RoleID"].ToString();

            //if (DateTime.Now.Hour < 12)
            //{
            //    AccessModel.greeting = "Good Morning!";
            //}
            //else if (DateTime.Now.Hour < 17)
            //{
            //    AccessModel.greeting = "Good Afternoon!";
            //}
            //else
            //{
            //    AccessModel.greeting = "Good Evening!";
            //}
            //AccessModel.Year = DateTime.Now.Year.ToString();
            return PartialView("~/Views/Shared/_NavigationPartial.cshtml", _AccessModel);
        }
    }
}

ExtraPortal/Views/Shared/_FooterPartial.cshtml
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">ExtraPortal © 2018 - @DateTime.Now.Year</span>
        </div>

        <div class="col-xs-6 col-sm-6 text-right hidden-xs">

        </div>
    </div>
</div>

ExtraPortal/Views/Shared/_HeaderPartial.cshtml
<!-- #HEADER -->
<header id="header">
    <div id="logo-group">

        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo"> <img src="~/Assets/img/logo.png" alt="HR Master"> </span>
        <!-- END LOGO PLACEHOLDER -->
        <!-- Note: The activity badge color changes when clicked and resets the number to 0
             Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
       
        
    </div>


    <!-- #TOGGLE LAYOUT BUTTONS -->
    <!-- pulled right: nav area -->
    <div class="pull-right">

        <!-- collapse menu button -->
        <div id="hide-menu" class="btn-header pull-right">
            <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
        </div>
        <!-- end collapse menu -->
        <!-- #MOBILE -->
       
        <!-- logout button -->
        <div id="logout" class="btn-header transparent pull-right">
            <span> <a href="/Security/SignOut" title="Sign Out" data-action="userLogout" data-logout-msg="Are you sure you want to sign out your session?"><i class="fa fa-sign-out"></i></a> </span>
        </div>
        <!-- end logout button -->
        <!-- search mobile button (this is hidden till mobile view port) -->
        <div id="search-mobile" class="btn-header transparent pull-right">
            <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
        </div>
        <!-- end search mobile button -->

    </div>
    <!-- end pulled right: nav area -->

</header>
<!-- END HEADER -->

ExtraPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>   
    <meta charset=" utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title> @ViewBag.Title - ExtraPortal </title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Basic Styles -->
    @*@Styles.Render("~/assets/extraportal")*@
    <link rel="stylesheet" type="text/css" media="screen" href="css/your_style.css">
    <link href="../../Assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../../Assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="../../Assets/css/smartadmin-production-plugins.min.css" rel="stylesheet" />
    <link href="../../Assets/css/smartadmin-production.min.css" rel="stylesheet" />
    <link href="../../Assets/css/smartadmin-rtl.min.css" rel="stylesheet" />
    <link href="../../Assets/css/smartadmin-skins.min.css" rel="stylesheet" />
    
    <!-- Custom Styles -->
    @*@Styles.Render("~/assets/custom")*@
    <link href="../../Assets/css/custom.css" rel="stylesheet" />
    <link href="../../Assets/plugins/select2/select2.min.css" rel="stylesheet" />
    
    <!-- FAVICONS -->
    <link rel="shortcut icon" href="../../Assets/img/favicon/favicon.png" type="image/x-icon">
    <link rel="icon" href="../../Assets/img/favicon/favicon.png" type="image/x-icon">
    <!-- #GOOGLE FONT -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- #APP SCREEN / ICONS -->
    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="../../Assets/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="../../Assets/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="../../Assets/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="../../Assets/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="../../Assets/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="../../Assets/img/splash/iphone.png" media="screen and (max-device-width: 320px)">

    @*@Scripts.Render("~/scripts/angular")*@
    <script src="../../Scripts/angular.min.js"></script>
    <script src="../../Scripts/Resources/ui-bootstrap-tpls-0.13.4.min.js"></script>
    
    @*<link href="../../Assets/plugins/autocomplete/jquery-ui.css" rel="stylesheet" />*@
</head>
<body class="smart-style-3 fixed-page-footer fixed-header fixed-ribbon">
    <!-- #HEADER -->
    @Html.Partial("_HeaderPartial")
    <!-- END HEADER -->

    <!-- #NAVIGATION -->
    @*@Html.Partial("_NavigationPartial")*@
    @Html.Action("ModuleAccess", "System")
    <!-- END NAVIGATION -->

    <!-- MAIN PANEL -->
    <div id="main" role="main">

        <!-- RIBBON -->
        @Html.Partial("_RibbonPartial")
        <!-- END RIBBON -->

        <!-- MAIN CONTENT -->
        <div id="content">
            <div id="loader" class="splash">
                <div>
                    <img src="../../Assets/img/ajax-loader.gif" />
                </div>
            </div>
            @RenderBody()
        </div>
        <!-- END MAIN CONTENT -->

    </div>
    <!-- END MAIN PANEL -->

    <!-- PAGE FOOTER -->
    @Html.Partial("_FooterPartial")
    <!-- END PAGE FOOTER -->

    <!-- PAGE FOOTER -->
    @Html.Partial("_ScriptsPartial")
    <!-- END PAGE FOOTER -->
    
    <script type="text/javascript">
        jQuery(function ($) {
            $('.js-example-basic-single').select2();
            $('.js-example-basic-multiple').select2({ minimumInputLength: 3 });

            $("#ClientArea").hide();
        })
    </script>
</body>
</html>

ExtraPortal/Views/Shared/_NavigationPartial.cshtml
@model ExtraPortal.Models.UserAccessRightsModel
<!-- #NAVIGATION -->
<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<aside id="left-panel">
    <!-- User info -->
    <div class="login-info">
        <div class="btn-group dropdown">
            <span class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
                <a href="javascript:void(0);">
                    <img src="~/Assets/img/avatars/male.png" alt="me" class="online" />
                    <span>
                        @Session["KE_UserName"]
                        
                    </span>
                    <i class="fa fa-angle-down"></i>
                </a>
            </span>
            <ul class="dropdown-menu">
                @*<li><a data-toggle="modal" href="#"><i class="fa fa-user"></i>&nbsp;My profile</a></li>*@
                <li><a href="/Security/SignOut" title="Sign Out" data-action="userLogout" data-logout-msg="Are you sure you want to sign out your session?"><i class="fa fa-sign-out"></i>&nbsp;Log Out</a></li>
            </ul>
        </div>
    </div>
    <!-- end user info -->
    <!-- NAVIGATION : This navigation is also responsive-->
    <nav>
        <ul>
            
            @foreach (var mainmenu in Model.mainmodule)
            {
                if (mainmenu.MainModuleID == 100)
                {
                    
                    if (TempData["MenuID"].ToString() == mainmenu.MainModuleName)
                    {
                        <li class="active">
                            <a href="@Url.Action("Dashboard", "Home") " title="Dashboard">
                                <i class="@mainmenu.MainModuleIcon"></i>
                                <span class="menu-item-parent">@mainmenu.MainModuleName</span>
                            </a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("Dashboard", "Home") " title="Dashboard">
                                <i class="@mainmenu.MainModuleIcon"></i>
                                <span class="menu-item-parent">@mainmenu.MainModuleName</span>
                            </a>
                        </li>
                    }

                }
                else
                {
                    <li>
                        <a href="#">
                            <i class="@mainmenu.MainModuleIcon"></i>
                            <span class="menu-item-parent">@mainmenu.MainModuleName</span>
                        </a>

                        <ul>
                            @foreach (var Module in Model.modules)
                            {
                                if (Module.MainModuleID == mainmenu.MainModuleID && TempData["MenuID"].ToString() == Module.ModuleName)
                                {
                                    <li class="active">
                                        <a href="@Url.Action(Module.Action, Module.Controller)">
                                            <i class="fa fa-angle-double-right"></i>
                                            @Module.ModuleName
                                        </a>
                                    </li>
                                }
                                else if(Module.MainModuleID == mainmenu.MainModuleID && TempData["MenuID"].ToString() != Module.ModuleName)
                                {
                                        <li>
                                            <a href="@Url.Action(Module.Action, Module.Controller)">
                                                <i class="fa fa-angle-double-right"></i>
                                                @Module.ModuleName
                                            </a>
                                        </li>
                                    
                                }
                            }
                        </ul>
                    </li>
                }
            }
        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>
</aside>
<!-- END NAVIGATION -->

ExtraPortal/Views/Shared/_RibbonPartial.cshtml
<!-- RIBBON -->
<div id="ribbon">

    <span class="ribbon-button-alignment">

    </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li><i class="fa fa-lg fa-fw fa-home"></i>  @ViewBag.PageTitle</li>
    </ol>    
</div>

<!-- END RIBBON -->

ExtraPortal/Views/Shared/_ScriptsPartial.cshtml
<!-- IMPORTANT: Mandatory Scripts -->
@*@Scripts.Render("~/scripts/mandatory")*@
<script src="../../Assets/js/libs/jquery-2.1.1.min.js"></script>
<script src="../../Assets/js/libs/jquery-ui-1.10.3.min.js"></script>

<!-- IMPORTANT: SmartAdmin Core -->
@*@Scripts.Render("~/scripts/extraportal")*@
<script src="../../Assets/js/app.config.js"></script>
<script src="../../Assets/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script>
<script src="../../Assets/js/bootstrap/bootstrap.min.js"></script>
<script src="../../Assets/js/notification/SmartNotification.min.js"></script>
<script src="../../Assets/js/smartwidgets/jarvis.widget.min.js"></script>
<script src="../../Assets/js/plugin/jquery-validate/jquery.validate.min.js"></script>
<script src="../../Assets/js/plugin/masked-input/jquery.maskedinput.min.js"></script>
<script src="../../Assets/js/plugin/select2/select2.min.js"></script>
<script src="../../Assets/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>
<script src="../../Assets/js/plugin/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<script src="../../Assets/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>
<script src="../../Assets/js/plugin/fastclick/fastclick.min.js"></script>
<script src="../../Assets/js/app.min.js"></script>

<!-- SmartChat UI : plugin -->
@*@Scripts.Render("~/scripts/smart-chat")*@

<!-- DataTables : plugin -->
@*@Scripts.Render("~/scripts/datatables")*@
<script src="../../Assets/js/plugin/datatables/jquery.dataTables.min.js"></script>
<script src="../../Assets/js/plugin/datatables/dataTables.colVis.min.js"></script>
<script src="../../Assets/js/plugin/datatables/dataTables.tableTools.min.js"></script>
<script src="../../Assets/js/plugin/datatables/dataTables.bootstrap.min.js"></script>
<script src="../../Assets/js/plugin/datatable-responsive/datatables.responsive.min.js"></script>

<!-- jQGrid : plugin -->
@*@Scripts.Render("~/scripts/jq-grid")*@

<!-- Forms : plugin -->
@*@Scripts.Render("~/scripts/forms")*@
<script src="../../Assets/js/plugin/jquery-form/jquery-form.min.js"></script>

<!-- Flot Chart Plugin: Flot Engine, Flot Resizer, Flot Tooltip, Morris, Sparkline, EasyPie -->
@*@Scripts.Render("~/scripts/charts")*@

<!-- Vector Maps Plugin: Vectormap engine, Vectormap language -->
@*@Scripts.Render("~/scripts/vector-map")*@

<!-- Full Calendar -->
@*@Scripts.Render("~/scripts/full-calendar")*@

<!-- Select 2 -->
@*@Scripts.Render("~/scripts/plugins")*@
<script src="../../Assets/plugins/select2/select2.min.js"></script>


<!-- DO NOT REMOVE : GLOBAL FUNCTIONS! -->
<script src="../../Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="../../Scripts/jquery.validate.min.js"></script>
<script src="../../Scripts/jquery.validate.unobtrusive.min.js"></script>

<script>
    $(document).ready(function () {
        $(".numbersonly").forceNumeric();
    });

    // forceNumeric() plug-in implementation
    jQuery.fn.forceNumeric = function () {
        return this.each(function () {
            $(this).keydown(function (e) {
                var key = e.which || e.keyCode;

                if (!e.shiftKey && !e.altKey && !e.ctrlKey &&
                    // numbers   
                    key >= 48 && key <= 57 ||
                    // Numeric keypad
                    key >= 96 && key <= 105 ||
                    // comma, period and minus, . on keypad
                   key == 190 || key == 188 || key == 109 || key == 110 ||
                    // Backspace and Tab and Enter
                   key == 8 || key == 9 || key == 13 ||
                    // Home and End
                   key == 35 || key == 36 ||
                    // left and right arrows
                   key == 37 || key == 39 ||
                    // Del and Ins
                   key == 46 || key == 45)
                    return true;

                return false;
            });
        });
    }


    $(document).ready(function () {
        pageSetUp();

        $(document).ready(function() {
            var success = @((TempData["Success"] != null).ToString().ToLower());

            if (success == true) {
                $.smallBox({
                    title : "Success",
                    content : "<i class='fa fa-check'></i> <i>Successfully!</i>",
                    color : "#739E73",
                    iconSmall : "fa fa-thumbs-up bounce animated",
                    timeout : 4000
                });
            }
        });

        $(document).ready(function() {
            var error = @((TempData["Error"] != null).ToString().ToLower());

            if (error == true) {
                $.smallBox({
                    title : "Error",
                    content : "<i class='fa fa-warning'></i> <i>Technical Error!</i>",
                    color : "#C46A69",
                    iconSmall : "fa fa-warning bounce animated",
                    timeout : 4000
                });
            }
        });

        /* BASIC ;*/
        var responsiveHelper_dt_basic = undefined;
        var responsiveHelper_datatable_fixed_column = undefined;
        var responsiveHelper_datatable_col_reorder = undefined;
        var responsiveHelper_datatable_tabletools = undefined;

        var breakpointDefinition = {
            tablet : 1024,
            phone : 480
        };

        $('#dt_basic').dataTable({
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
                "t"+
                "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
            "autoWidth" : true,
            "preDrawCallback" : function() {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper_dt_basic) {
                    responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
                }
            },
            "rowCallback" : function(nRow) {
                responsiveHelper_dt_basic.createExpandIcon(nRow);
            },
            "drawCallback" : function(oSettings) {
                responsiveHelper_dt_basic.respond();
            },
				    
            "bSort": false
				    
        })
        /* END BASIC */ 

        $('#dt_basic1').dataTable({
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
                "t"+
                "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
            "autoWidth" : true,
            "preDrawCallback" : function() {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper_dt_basic) {
                    responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
                }
            },
            "rowCallback" : function(nRow) {
                responsiveHelper_dt_basic.createExpandIcon(nRow);
            },
            "drawCallback" : function(oSettings) {
                responsiveHelper_dt_basic.respond();
            },
				    
            "bSort": false
				    
        })


        /* COLUMN FILTER  */
        var otable = $('#datatable_fixed_column').DataTable({
            //"bFilter": false,
            //"bInfo": false,
            //"bLengthChange": false
            //"bAutoWidth": false,
            //"bPaginate": false,
            //"bStateSave": true // saves sort state using localStorage
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>"+
                    "t"+
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
            "autoWidth" : true,
            "preDrawCallback" : function() {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper_datatable_fixed_column) {
                    responsiveHelper_datatable_fixed_column = new ResponsiveDatatablesHelper($('#datatable_fixed_column'), breakpointDefinition);
                }
            },
            "rowCallback" : function(nRow) {
                responsiveHelper_datatable_fixed_column.createExpandIcon(nRow);
            },
            "drawCallback" : function(oSettings) {
                responsiveHelper_datatable_fixed_column.respond();
            }

        });

        // custom toolbar
        $("div.toolbar").html('<div class="text-right"><img src="img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');

        // Apply the filter
        $("#datatable_fixed_column thead th input[type=text]").on( 'keyup change', function () {

            otable
                .column( $(this).parent().index()+':visible' )
                .search( this.value )
                .draw();

        } );
        /* END COLUMN FILTER */

        /* COLUMN SHOW - HIDE */
        $('#datatable_col_reorder').dataTable({
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'C>r>"+
                    "t"+
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
            "autoWidth" : true,
            "preDrawCallback" : function() {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper_datatable_col_reorder) {
                    responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
                }
            },
            "rowCallback" : function(nRow) {
                responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
            },
            "drawCallback" : function(oSettings) {
                responsiveHelper_datatable_col_reorder.respond();
            }
        });

        /* END COLUMN SHOW - HIDE */

        /* TABLETOOLS */
        $('#datatable_tabletools').dataTable({

            // Tabletools options:
            //   https://datatables.net/extensions/tabletools/button_options
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
                    "t"+
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
            "oTableTools": {
                "aButtons": [
                "copy",
                "csv",
                "xls",
                   {
                       "sExtends": "pdf",
                       "sTitle": "SmartAdmin_PDF",
                       "sPdfMessage": "SmartAdmin PDF Export",
                       "sPdfSize": "letter"
                   },
                   {
                       "sExtends": "print",
                       "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
                   }
                ],
                "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
            },
            "autoWidth" : true,
            "preDrawCallback" : function() {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper_datatable_tabletools) {
                    responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
                }
            },
            "rowCallback" : function(nRow) {
                responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
            },
            "drawCallback" : function(oSettings) {
                responsiveHelper_datatable_tabletools.respond();
            }
        });

        /* END TABLETOOLS */


    });

    setTimeout(function () {
        $('#loader').remove();
    }, 1000);

    $(document).ready(function () {
        $("#dt_subscribers").dataTable({
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "ajax": {
                "url": "/AppUSSD/LoadData",
                "type": "POST",
                "datatype": "json"
            },
            "columns": [
                    { "data": "ClientID", "name": "ClientID", "autoWidth": true },
                    { "data": "Name", "name": "Name", "autoWidth": true },
                    { "data": "Mobile", "name": "Mobile", "autoWidth": true },
                    { "data": "Gender", "name": "Gender", "autoWidth": true },
                    { "data": "IsBlocked", "name": "IsBlocked", "autoWidth": true }
            ]
        });
    });

    $('.js-example-basic-single').select2();
</script>

@if (@Model is HelperResult)
{
    @Model
}